//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DiamondWebService.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReportCheckWSImplPortBinding", Namespace="http://service.reportcheck.model.ngs.com/")]
    public partial class ReportCheckWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback processRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReportCheckDateResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback downloadPDFReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback processRequest1OperationCompleted;
        
        private System.Threading.SendOrPostCallback getColoredStonePearlResultsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReportCheckWS() {
            this.Url = global::DiamondWebService.Properties.Settings.Default.DiamondWebService_WebReference_ReportCheckWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event processRequestCompletedEventHandler processRequestCompleted;
        
        /// <remarks/>
        public event getReportCheckDateResultCompletedEventHandler getReportCheckDateResultCompleted;
        
        /// <remarks/>
        public event downloadPDFReportCompletedEventHandler downloadPDFReportCompleted;
        
        /// <remarks/>
        public event processRequest1CompletedEventHandler processRequest1Completed;
        
        /// <remarks/>
        public event getColoredStonePearlResultsCompletedEventHandler getColoredStonePearlResultsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.reportcheck.model.ngs.com/", ResponseNamespace="http://service.reportcheck.model.ngs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processRequest([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("processRequest", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processRequestAsync(string arg0) {
            this.processRequestAsync(arg0, null);
        }
        
        /// <remarks/>
        public void processRequestAsync(string arg0, object userState) {
            if ((this.processRequestOperationCompleted == null)) {
                this.processRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessRequestOperationCompleted);
            }
            this.InvokeAsync("processRequest", new object[] {
                        arg0}, this.processRequestOperationCompleted, userState);
        }
        
        private void OnprocessRequestOperationCompleted(object arg) {
            if ((this.processRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processRequestCompleted(this, new processRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.reportcheck.model.ngs.com/", ResponseNamespace="http://service.reportcheck.model.ngs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getReportCheckDateResult([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("getReportCheckDateResult", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getReportCheckDateResultAsync(string arg0) {
            this.getReportCheckDateResultAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getReportCheckDateResultAsync(string arg0, object userState) {
            if ((this.getReportCheckDateResultOperationCompleted == null)) {
                this.getReportCheckDateResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReportCheckDateResultOperationCompleted);
            }
            this.InvokeAsync("getReportCheckDateResult", new object[] {
                        arg0}, this.getReportCheckDateResultOperationCompleted, userState);
        }
        
        private void OngetReportCheckDateResultOperationCompleted(object arg) {
            if ((this.getReportCheckDateResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReportCheckDateResultCompleted(this, new getReportCheckDateResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.reportcheck.model.ngs.com/", ResponseNamespace="http://service.reportcheck.model.ngs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] downloadPDFReport([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("downloadPDFReport", new object[] {
                        arg0});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void downloadPDFReportAsync(string arg0) {
            this.downloadPDFReportAsync(arg0, null);
        }
        
        /// <remarks/>
        public void downloadPDFReportAsync(string arg0, object userState) {
            if ((this.downloadPDFReportOperationCompleted == null)) {
                this.downloadPDFReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownloadPDFReportOperationCompleted);
            }
            this.InvokeAsync("downloadPDFReport", new object[] {
                        arg0}, this.downloadPDFReportOperationCompleted, userState);
        }
        
        private void OndownloadPDFReportOperationCompleted(object arg) {
            if ((this.downloadPDFReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downloadPDFReportCompleted(this, new downloadPDFReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.reportcheck.model.ngs.com/", ResponseNamespace="http://service.reportcheck.model.ngs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processRequest1([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("processRequest1", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processRequest1Async(string arg0) {
            this.processRequest1Async(arg0, null);
        }
        
        /// <remarks/>
        public void processRequest1Async(string arg0, object userState) {
            if ((this.processRequest1OperationCompleted == null)) {
                this.processRequest1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessRequest1OperationCompleted);
            }
            this.InvokeAsync("processRequest1", new object[] {
                        arg0}, this.processRequest1OperationCompleted, userState);
        }
        
        private void OnprocessRequest1OperationCompleted(object arg) {
            if ((this.processRequest1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processRequest1Completed(this, new processRequest1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.reportcheck.model.ngs.com/", ResponseNamespace="http://service.reportcheck.model.ngs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getColoredStonePearlResults([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
            object[] results = this.Invoke("getColoredStonePearlResults", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getColoredStonePearlResultsAsync(string arg0) {
            this.getColoredStonePearlResultsAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getColoredStonePearlResultsAsync(string arg0, object userState) {
            if ((this.getColoredStonePearlResultsOperationCompleted == null)) {
                this.getColoredStonePearlResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetColoredStonePearlResultsOperationCompleted);
            }
            this.InvokeAsync("getColoredStonePearlResults", new object[] {
                        arg0}, this.getColoredStonePearlResultsOperationCompleted, userState);
        }
        
        private void OngetColoredStonePearlResultsOperationCompleted(object arg) {
            if ((this.getColoredStonePearlResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getColoredStonePearlResultsCompleted(this, new getColoredStonePearlResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void processRequestCompletedEventHandler(object sender, processRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getReportCheckDateResultCompletedEventHandler(object sender, getReportCheckDateResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReportCheckDateResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReportCheckDateResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void downloadPDFReportCompletedEventHandler(object sender, downloadPDFReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downloadPDFReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downloadPDFReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void processRequest1CompletedEventHandler(object sender, processRequest1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processRequest1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processRequest1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getColoredStonePearlResultsCompletedEventHandler(object sender, getColoredStonePearlResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getColoredStonePearlResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getColoredStonePearlResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591